#ifndef INA229_H
#define INA229_H

#include <stdint.h>
#include <stdbool.h>

typedef struct{
    void *spi_inst; //Pointer to SPI instance generated by sys config
    uint32_t cs_port; //Chip select port
    uint32_t cs_pin; //Chip select pin
    float r_shunt_ohms; //Shunt resistance value in ohms
    float current_lsb; //Current resolution
    uint8_t adc_range; /* if adc_range = 0 => range is 163.84mV meaning more range but less resolution
                        if adc_range = 1 => range is 40.96 mV meaning less range but more resolution*/
} ina229_t;

//Driver return codes
typedef enum {
    INA229_OK = 0,
    INA229_ERR_ARG,
    INA229_ERR_TIMEOUT,
    INA229_ERR_SPI
} ina229_status_t;

/* Register Map */
/* Value in hex | Name | Description | Size in bits */

// 0h CONFIG Configuration 16 
#define INA229_REG_CONFIG 0x00

//1h ADC_CONFIG ADC Configuration 16 
#define INA229_REG_ADC_CONFIG 0x01

//2h SHUNT_CAL Shunt Calibration 16 
#define INA229_REG_SHUNT_CAL 0x02

//3h SHUNT_TEMPCO Shunt Temperature Coefficient 16 
#define INA229_REG_SHUNT_TEMPCO 0x03

//4h VSHUNT Shunt Voltage Measurement 24 
#define INA229_REG_VSHUNT 0x04

//5h VBUS Bus Voltage Measurement 24 
#define INA229_REG_VBUS 0x05

//6h DIETEMP Temperature Measurement 16 
#define INA229_REG_DIETEMP 0x06

//7h CURRENT Current Result 24 
#define INA229_REG_CURRENT 0x07

//8h POWER Power Result 24 
#define INA229_REG_POWER 0x08

//9h ENERGY Energy Result 40 
#define INA229_REG_ENERGY 0x09

//Ah CHARGE Charge Result 40 
#define INA229_REG_CHARGE 0x0A

//Bh DIAG_ALRT Diagnostic Flags and Alert 16 
#define INA229_REG_DIAG_ALRT 0x0B

//Ch SOVL Shunt Overvoltage Threshold 16 
#define INA229_REG_SOVL 0x0C

//Dh SUVL Shunt Undervoltage Threshold 16
#define INA229_REG_SUVL 0x0D

//Eh BOVL Bus Overvoltage Threshold 16 
#define INA229_REG_BOVL 0x0E

//Fh BUVL Bus Undervoltage Threshold 16 
#define INA229_REG_BUVL 0x0F

//10h TEMP_LIMIT Temperature Over-Limit Threshold 16 
#define INA229_REG_TEMP_LIMIT 0x10

//11h PWR_LIMIT Power Over-Limit Threshold 16 
#define INA229_REG_PWR_LIMIT 0x11

//3Eh MANUFACTURER_ID Manufacturer ID 16 
#define INA229_REG_MANUFACTURER_ID 0X3E

//3Fh DEVICE_ID Device ID 16
#define INA229_REG_DEVICE_ID 0x3F

//Init function prototype
ina229_status_t ina229_init(ina229_t *dev);

/*Core read and write functions prototypes, all the HAL function use these ones, 
they are the ones who implements the SPI protocol*/
ina229_status_t ina229_read_reg16(ina229_t *dev, uint8_t reg, uint16_t *value);
ina229_status_t ina229_read_reg24(ina229_t *dev, uint8_t reg, uint32_t *value);
ina229_status_t ina229_read_reg40(ina229_t *dev, uint8_t reg, uint64_t *value);

ina229_status_t ina229_write_reg16(ina229_t *dev, uint8_t reg, uint16_t value);

/*Abstraction layer for registers*/

//INA229 write functions prototypes
ina229_status_t ina229_write_configuration(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_adc_configuration(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_shunt_calibration(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_shunt_temperature_coefficient(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_flags(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_shunt_overvoltage_threshold(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_shunt_undervoltage_threshold(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_bus_overvoltage_threshold(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_bus_undervoltage_threshold(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_temperature_over_limit_threshold(ina229_t *dev, uint16_t value);
ina229_status_t ina229_write_power_over_limit_threshold(ina229_t *dev, uint16_t value);


//INA229 read functions prototypes
ina229_status_t ina229_read_manufacturer_id(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_device_id(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_adc_configuration(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_configuration(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_shunt_calibration(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_shunt_temperature_coefficient(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_shunt_voltage(ina229_t *dev, float *value);
ina229_status_t ina229_read_bus_voltage(ina229_t *dev, float *value);
ina229_status_t ina229_read_die_temperature(ina229_t *dev, float *value);
ina229_status_t ina229_read_current(ina229_t *dev, float *value);
ina229_status_t ina229_read_power(ina229_t *dev, float *value);
ina229_status_t ina229_read_energy(ina229_t *dev, float *value);
ina229_status_t ina229_read_charge(ina229_t *dev, float *value);
ina229_status_t ina229_read_flags(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_shunt_overvoltage_threshold(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_shunt_undervoltage_threshold(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_bus_overvoltage_threshold(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_bus_undervoltage_threshold(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_temperature_over_limit_threshold(ina229_t *dev, uint16_t *value);
ina229_status_t ina229_read_power_over_limit_threshold(ina229_t *dev, uint16_t *value);

#endif //INA229_H